spring:
  ai:
    chat:
      memory:
        repository:
          jdbc:
            # 初始化数据库的时机 always: 总是初始化, never: 从不初始化, embedded: 嵌入式数据库(H2、HSQL、Derby 等)时初始化
            initialize-schema: always
            # 初始化数据库的脚本位置, 1.0.0默认有以下脚本hsqldb/mariadb/postgresql/sqlserver, 无mysql
            schema: classpath:org/springframework/ai/chat/memory/repository/jdbc/schema-@@platform@@.sql
            # 在初始化脚本中使用的平台（如果使用@@platform@@占位符）,默认无输入时自动检测
            platform: 
      