
# chatanywhere
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      # 使用openai时, base-url配置时，要把/v1去掉，Spring会自动添加/v1/chat/completions，
      base-url: https://api.chatanywhere.tech
      # 聊天模型
      chat:
        options:
          model: gpt-4o-mini
#          model: gpt-4o 
#          model: gpt-4-turbo
#          model: gpt-3.5-turbo
      # 嵌入模型 文本向量用
      embedding:
        options:
          model: text-embedding-ada-002
#          model: text-embedding-3-large
#          model: text-embedding-3-small
      # 图片生成模型
      image:
        options:
          model: dall-e-3
#          model: dall-e-2
      # 音频模型
      audio:
        # 语音转文字
        transcription:
          options:
            model: whisper-1
        # 文字转语音
        speech:
          options:
            model: tts-1 
#            model: tts-1-hd
      # 审核模型, 检测文本是否包含敏感信息
      moderation:
        options:
          model: text-moderation-latest
        