spring:
  ai:
    model:
      # 默认值,实际无需配置, 要禁用，spring.ai.model.chat=none禁用后允许配置多个模型
#      chat: openai 
  application:
    name: springboot-21-ai
  profiles:
    active:
#        - mysql
        - postgresql 
        - openai
        - deepseek
        - chat-memory
        - vector-pg
---
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG