spring:
  main:
    # NOTE: You must disable the banner and the console logging 
    # to allow the STDIO transport to work !!!
    banner-mode: off
  profiles:
    active: 
      - mcp-server
---
logging:
  file:
    name: logs/starter-webflux-server.log