spring:
  application:
    name: ai-mcp-server
  main:
    web-application-type: none
  ai:
    mcp:
      client:
        sse:
          connections:
            server1:          
              url: http://localhost:8080
        request-timeout: 300s