
# 官方文档地址https://kafka.apache.org/documentation/
spring:
  kafka:
    # 注意: 如果是用docker启动的kafka,其名称为kafka,在docker内部网卡通信时能正确解析
    # 但在外部运行时无法正确解析, 此时需要修改host文件,将kafka对应docker容器的名称指向docker宿主机的ip
    bootstrap-servers: 192.168.56.104:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



