server:
  port: 80
spring:
  data:
    redis:
      host: 192.168.56.106
      port: 6379
      client-type: jedis
      jedis:
        pool:
          # 是否启用连接池
          enabled: true
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8
          max-idle: 8


